"""Execution boundary for the local research workbench."""
from __future__ import annotations
from typing import Protocol, Callable


class InteractiveResearchRunner(Protocol):
    def run(self, workspace: str, request: dict, progress: Callable[[str], None], cancelled: Callable[[], bool]) -> None: ...


class InteractiveResearchRepository(Protocol):
    def tree(self) -> dict: ...
    def process(self) -> dict: ...
    def current_job(self) -> dict | None: ...
    def prepare(self, proposal: dict) -> dict: ...
    def save_job(self, job: dict) -> None: ...
    def validate_and_publish(self, job: dict) -> None: ...
